package com.mycompany.broker.view;

import com.mycompany.broker.model.Graphic;
import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionListener;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author dam2_alu09@inf.ald
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        Graphic.addGraphic(this.getGraphicPanel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTabbedPane = new javax.swing.JTabbedPane();
        graphicPanel = new javax.swing.JPanel();
        agentsPanel = new javax.swing.JPanel();
        agentsScrollPane = new javax.swing.JScrollPane();
        agentsTable = new javax.swing.JTable();
        editButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        operationsPanel = new javax.swing.JPanel();
        agentsOperationScrollPane = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout graphicPanelLayout = new javax.swing.GroupLayout(graphicPanel);
        graphicPanel.setLayout(graphicPanelLayout);
        graphicPanelLayout.setHorizontalGroup(
            graphicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );
        graphicPanelLayout.setVerticalGroup(
            graphicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
        );

        mainTabbedPane.addTab("Bolsa", graphicPanel);

        agentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Balance", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        agentsScrollPane.setViewportView(agentsTable);

        editButton.setText("Editar...");

        removeButton.setText("Eliminar");

        addButton.setText("Añadir...");

        jButton1.setText("Operaciones...");

        javax.swing.GroupLayout agentsPanelLayout = new javax.swing.GroupLayout(agentsPanel);
        agentsPanel.setLayout(agentsPanelLayout);
        agentsPanelLayout.setHorizontalGroup(
            agentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agentsPanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(removeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(agentsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        agentsPanelLayout.setVerticalGroup(
            agentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agentsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(agentsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(agentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(editButton)
                    .addComponent(removeButton)
                    .addComponent(jButton1))
                .addGap(26, 26, 26))
        );

        mainTabbedPane.addTab("Agentes", agentsPanel);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        agentsOperationScrollPane.setViewportView(jList2);

        javax.swing.GroupLayout operationsPanelLayout = new javax.swing.GroupLayout(operationsPanel);
        operationsPanel.setLayout(operationsPanelLayout);
        operationsPanelLayout.setHorizontalGroup(
            operationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(operationsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(agentsOperationScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(265, Short.MAX_VALUE))
        );
        operationsPanelLayout.setVerticalGroup(
            operationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(operationsPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(agentsOperationScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Operaciones", operationsPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addAAddButtonActionListener(ActionListener al) {
        this.addButton.addActionListener(al);
    }

    public JButton getAddButton() {
        return addButton;
    }

    public void setAddButton(JButton addButton) {
        this.addButton = addButton;
    }

    public JPanel getAgentsPanel() {
        return agentsPanel;
    }

    public void setAgentsPanel(JPanel agentsPanel) {
        this.agentsPanel = agentsPanel;
    }

    public JButton getEditButton() {
        return editButton;
    }

    public void setEditButton(JButton editButton) {
        this.editButton = editButton;
    }

    public JPanel getGraphicPanel() {
        return graphicPanel;
    }

    public void setGraphicPanel(JPanel graphicPanel) {
        this.graphicPanel = graphicPanel;
    }

    public JScrollPane getjScrollPane1() {
        return agentsScrollPane;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.agentsScrollPane = jScrollPane1;
    }

    public JTable getjTable1() {
        return agentsTable;
    }

    public void setjTable1(JTable jTable1) {
        this.agentsTable = jTable1;
    }

    public JTabbedPane getMainTabbedPane() {
        return mainTabbedPane;
    }

    public void setMainTabbedPane(JTabbedPane mainTabbedPane) {
        this.mainTabbedPane = mainTabbedPane;
    }

    public JPanel getOperationsPanel() {
        return operationsPanel;
    }

    public void setOperationsPanel(JPanel operationsPanel) {
        this.operationsPanel = operationsPanel;
    }

    public JButton getRemoveButton() {
        return removeButton;
    }

    public void setRemoveButton(JButton removeButton) {
        this.removeButton = removeButton;
    }

    public void addRow(Vector row) {
        DefaultTableModel model = (DefaultTableModel) this.agentsTable.getModel();
        model.addRow(row);
    }
    
    public String getSelectedComputer(){
        int selectedRow = this.agentsTable.getSelectedRow();
        String s = (String) this.agentsTable.getModel().getValueAt(selectedRow, 0);
        System.out.println(s);
        return s;
    }
    
    public void clearTable() {
        DefaultTableModel model = (DefaultTableModel) this.agentsTable.getModel();
        model.setRowCount(0);
        agentsTable.clearSelection();
        agentsTable.revalidate();
        agentsTable.repaint();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JScrollPane agentsOperationScrollPane;
    private javax.swing.JPanel agentsPanel;
    private javax.swing.JScrollPane agentsScrollPane;
    private javax.swing.JTable agentsTable;
    private javax.swing.JButton editButton;
    private javax.swing.JPanel graphicPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JPanel operationsPanel;
    private javax.swing.JButton removeButton;
    // End of variables declaration//GEN-END:variables
}
