package com.mycompany.broker.view;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author dam2_alu04@inf.ald
 */
public class OperationsJDialog extends javax.swing.JDialog {

    /**
     * Creates new form OperationsJDialog
     */
    public OperationsJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        operationsTabbedPane = new javax.swing.JTabbedPane();
        sellPanel = new javax.swing.JPanel();
        priceBLabel = new javax.swing.JLabel();
        quantityBLabel = new javax.swing.JLabel();
        priceBTextField = new javax.swing.JTextField();
        quantityBTextField = new javax.swing.JTextField();
        cancelBButton = new javax.swing.JButton();
        acceptBButton = new javax.swing.JButton();
        buyPanel = new javax.swing.JPanel();
        priceSLabel = new javax.swing.JLabel();
        quantitySLabel = new javax.swing.JLabel();
        priceSTextField = new javax.swing.JTextField();
        quantitySTextField = new javax.swing.JTextField();
        cancelSButton = new javax.swing.JButton();
        acceptSButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        priceBLabel.setText("Precio:*");

        quantityBLabel.setText("Cantidad:*");

        cancelBButton.setText("Cancelar");

        acceptBButton.setText("Aceptar");

        javax.swing.GroupLayout sellPanelLayout = new javax.swing.GroupLayout(sellPanel);
        sellPanel.setLayout(sellPanelLayout);
        sellPanelLayout.setHorizontalGroup(
            sellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sellPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quantityBLabel)
                    .addComponent(priceBLabel))
                .addGap(18, 18, 18)
                .addGroup(sellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(priceBTextField)
                    .addComponent(quantityBTextField))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sellPanelLayout.createSequentialGroup()
                .addComponent(acceptBButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(cancelBButton))
        );
        sellPanelLayout.setVerticalGroup(
            sellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sellPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceBLabel)
                    .addComponent(priceBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityBLabel)
                    .addComponent(quantityBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(sellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBButton)
                    .addComponent(acceptBButton))
                .addContainerGap())
        );

        operationsTabbedPane.addTab("Comprar", sellPanel);

        priceSLabel.setText("Precio:*");

        quantitySLabel.setText("Cantidad:*");

        cancelSButton.setText("Cancelar");

        acceptSButton.setText("Aceptar");

        javax.swing.GroupLayout buyPanelLayout = new javax.swing.GroupLayout(buyPanel);
        buyPanel.setLayout(buyPanelLayout);
        buyPanelLayout.setHorizontalGroup(
            buyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quantitySLabel)
                    .addComponent(priceSLabel))
                .addGap(18, 18, 18)
                .addGroup(buyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(priceSTextField)
                    .addComponent(quantitySTextField))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buyPanelLayout.createSequentialGroup()
                .addComponent(acceptSButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(cancelSButton))
        );
        buyPanelLayout.setVerticalGroup(
            buyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceSLabel)
                    .addComponent(priceSTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(buyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantitySLabel)
                    .addComponent(quantitySTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(buyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelSButton)
                    .addComponent(acceptSButton))
                .addContainerGap())
        );

        operationsTabbedPane.addTab("Vender", buyPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(operationsTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(operationsTabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addAcceptBButtonActionListener(ActionListener al){
        this.acceptBButton.addActionListener(al);
    }
    
    public void addAcceptSButtonActionListener(ActionListener al){
        this.acceptSButton.addActionListener(al);
    }
    
    public void addCancelBButtonActionListener(ActionListener al){
        this.cancelBButton.addActionListener(al);
    }
    
    public void addCancelSButtonActionListener(ActionListener al){
        this.cancelSButton.addActionListener(al);
    }
    
    public JButton getAcceptBButton() {
        return acceptBButton;
    }

    public void setAcceptBButton(JButton acceptBButton) {
        this.acceptBButton = acceptBButton;
    }

    public JButton getAcceptSButton() {
        return acceptSButton;
    }

    public void setAcceptSButton(JButton acceptSButton) {
        this.acceptSButton = acceptSButton;
    }

    public JButton getCancelBButton() {
        return cancelBButton;
    }

    public void setCancelBButton(JButton cancelBButton) {
        this.cancelBButton = cancelBButton;
    }

    public JButton getCancelSButton() {
        return cancelSButton;
    }

    public void setCancelSButton(JButton cancelSButton) {
        this.cancelSButton = cancelSButton;
    }

    public JTextField getPriceBTextField() {
        return priceBTextField;
    }

    public void setPriceBTextField(JTextField priceBTextField) {
        this.priceBTextField = priceBTextField;
    }

    public JTextField getPriceSTextField() {
        return priceSTextField;
    }

    public void setPriceSTextField(JTextField priceSTextField) {
        this.priceSTextField = priceSTextField;
    }

    public JTextField getQuantityBTextField() {
        return quantityBTextField;
    }

    public void setQuantityBTextField(JTextField quantityBTextField) {
        this.quantityBTextField = quantityBTextField;
    }

    public JTextField getQuantitySTextField() {
        return quantitySTextField;
    }

    public void setQuantitySTextField(JTextField quantitySTextField) {
        this.quantitySTextField = quantitySTextField;
    }
    
    public String getPriceB() {
        return priceBTextField.getText();
    }

    public void setPriceB(String priceB) {
        this.priceBTextField.setText(priceB);
    }

    public String getPriceS() {
        return priceSTextField.getText();
    }

    public void setPriceS(String priceS) {
        this.priceSTextField.setText(priceS);
    }

    public String getQuantityB() {
        return quantityBTextField.getText();
    }

    public void setQuantityB(String quantityB) {
        this.quantityBTextField.setText(quantityB);
    }

    public String getQuantityS() {
        return quantitySTextField.getText();
    }

    public void setQuantityS(String quantityS) {
        this.quantitySTextField.setText(quantityS);
    }

    public void enableDisableTextFieldsB(boolean enableDisable){
        priceBTextField.setEnabled(enableDisable);
        quantityBTextField.setEnabled(enableDisable);
        
    }
    
    public void enableDisableTextFieldsS(boolean enableDisable){
        priceSTextField.setEnabled(enableDisable);
        quantitySTextField.setEnabled(enableDisable);
        
    }
    
    public void enableDisableAcceptCancelBButton(boolean enableDisable){
        this.acceptBButton.setEnabled(enableDisable);
        this.cancelBButton.setEnabled(enableDisable);
    }
    
    public void enableDisableAcceptCancelSButton(boolean enableDisable){
        this.acceptSButton.setEnabled(enableDisable);
        this.cancelSButton.setEnabled(enableDisable);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptBButton;
    private javax.swing.JButton acceptSButton;
    private javax.swing.JPanel buyPanel;
    private javax.swing.JButton cancelBButton;
    private javax.swing.JButton cancelSButton;
    private javax.swing.JTabbedPane operationsTabbedPane;
    private javax.swing.JLabel priceBLabel;
    private javax.swing.JTextField priceBTextField;
    private javax.swing.JLabel priceSLabel;
    private javax.swing.JTextField priceSTextField;
    private javax.swing.JLabel quantityBLabel;
    private javax.swing.JTextField quantityBTextField;
    private javax.swing.JLabel quantitySLabel;
    private javax.swing.JTextField quantitySTextField;
    private javax.swing.JPanel sellPanel;
    // End of variables declaration//GEN-END:variables
}
