package com.mycompany.broker.view;

import com.mycompany.broker.model.Graphic;
import java.awt.BorderLayout;
import java.awt.event.ActionListener;
import java.util.Vector;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author dam2_alu09@inf.ald
 */
public class MainJFrame extends javax.swing.JFrame {
    private Graphic graphic;
    private JButton editOrderButton;
    private JButton cancelOrderButton;
    private JButton demoButton;

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        setTitle("Stock Broker");
        setSize(900, 600);
        setLocationRelativeTo(null);
        installOrdersButtons();
        agentsTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        operationsTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        hideOrderIdColumn();
        graphic = Graphic.addGraphic(this.getGraphicPanel());
    }

    private void installOrdersButtons() {
        editOrderButton = new JButton("Edit selected");
        cancelOrderButton = new JButton("Cancel selected");
        demoButton = new JButton("Load demo data");

        JPanel buttonsPanel = new JPanel();
        buttonsPanel.add(editOrderButton);
        buttonsPanel.add(cancelOrderButton);
        buttonsPanel.add(demoButton);

        operationsPanel.removeAll();
        operationsPanel.setLayout(new BorderLayout(8, 8));
        operationsPanel.add(agentsScrollPane1, BorderLayout.CENTER);
        operationsPanel.add(buttonsPanel, BorderLayout.SOUTH);
        operationsPanel.revalidate();
        operationsPanel.repaint();
    }

    private void hideOrderIdColumn() {
        operationsTable.getColumnModel().getColumn(0).setMinWidth(0);
        operationsTable.getColumnModel().getColumn(0).setMaxWidth(0);
        operationsTable.getColumnModel().getColumn(0).setPreferredWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTabbedPane = new javax.swing.JTabbedPane();
        graphicPanel = new javax.swing.JPanel();
        agentsPanel = new javax.swing.JPanel();
        agentsScrollPane = new javax.swing.JScrollPane();
        agentsTable = new javax.swing.JTable();
        addButton = new javax.swing.JButton();
        operationsButton = new javax.swing.JButton();
        operationsPanel = new javax.swing.JPanel();
        agentsScrollPane1 = new javax.swing.JScrollPane();
        operationsTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout graphicPanelLayout = new javax.swing.GroupLayout(graphicPanel);
        graphicPanel.setLayout(graphicPanelLayout);
        graphicPanelLayout.setHorizontalGroup(
            graphicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );
        graphicPanelLayout.setVerticalGroup(
            graphicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
        );

        mainTabbedPane.addTab("Market", graphicPanel);

        agentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Balance", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        agentsScrollPane.setViewportView(agentsTable);

        addButton.setText("Add...");

        operationsButton.setText("Orders...");

        javax.swing.GroupLayout agentsPanelLayout = new javax.swing.GroupLayout(agentsPanel);
        agentsPanel.setLayout(agentsPanelLayout);
        agentsPanelLayout.setHorizontalGroup(
            agentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agentsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(operationsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addButton)
                .addContainerGap())
            .addComponent(agentsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
        );
        agentsPanelLayout.setVerticalGroup(
            agentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agentsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(agentsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(agentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(operationsButton))
                .addGap(26, 26, 26))
        );

        mainTabbedPane.addTab("Agents", agentsPanel);

        operationsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Type", "Limit price", "Quantity", "Open", "Agent", "Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        agentsScrollPane1.setViewportView(operationsTable);

        javax.swing.GroupLayout operationsPanelLayout = new javax.swing.GroupLayout(operationsPanel);
        operationsPanel.setLayout(operationsPanelLayout);
        operationsPanelLayout.setHorizontalGroup(
            operationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(operationsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(agentsScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                .addContainerGap())
        );
        operationsPanelLayout.setVerticalGroup(
            operationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(agentsScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
        );

        mainTabbedPane.addTab("Orders", operationsPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addAddButtonActionListener(ActionListener al) {
        this.addButton.addActionListener(al);
    }
    
    public void addOperationsButtonActionListener(ActionListener al) {
        this.operationsButton.addActionListener(al);
    }

    public void addEditOrderButtonActionListener(ActionListener al) {
        this.editOrderButton.addActionListener(al);
    }

    public void addCancelOrderButtonActionListener(ActionListener al) {
        this.cancelOrderButton.addActionListener(al);
    }

    public void addDemoButtonActionListener(ActionListener al) {
        this.demoButton.addActionListener(al);
    }

    public JButton getAddButton() {
        return addButton;
    }

    public void setAddButton(JButton addButton) {
        this.addButton = addButton;
    }

    public JPanel getAgentsPanel() {
        return agentsPanel;
    }

    public void setAgentsPanel(JPanel agentsPanel) {
        this.agentsPanel = agentsPanel;
    }

    public JPanel getGraphicPanel() {
        return graphicPanel;
    }

    public void setGraphicPanel(JPanel graphicPanel) {
        this.graphicPanel = graphicPanel;
    }

    public JScrollPane getjScrollPane1() {
        return agentsScrollPane;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.agentsScrollPane = jScrollPane1;
    }

    public JTable getAgentsTable() {
        return agentsTable;
    }

    public void setjTable1(JTable AgentsTable) {
        this.agentsTable = AgentsTable;
    }

    public JTabbedPane getMainTabbedPane() {
        return mainTabbedPane;
    }

    public void setMainTabbedPane(JTabbedPane mainTabbedPane) {
        this.mainTabbedPane = mainTabbedPane;
    }

    public JPanel getOperationsPanel() {
        return operationsPanel;
    }

    public void setOperationsPanel(JPanel operationsPanel) {
        this.operationsPanel = operationsPanel;
    }
    
    public void addAgentRow(Vector row) {
        DefaultTableModel model = (DefaultTableModel) this.agentsTable.getModel();
        model.addRow(row);
    }
    
    public void addOperationRow(Vector row) {
        DefaultTableModel model = (DefaultTableModel) this.operationsTable.getModel();
        model.addRow(row);
    }
    
    public int getSelectedAgent(){
        return this.agentsTable.getSelectedRow();
    }

    public int getSelectedOrder(){
        return this.operationsTable.getSelectedRow();
    }

    public Long getSelectedOrderId() {
        int row = getSelectedOrder();
        if (row < 0) {
            return null;
        }
        Object value = operationsTable.getValueAt(row, 0);
        if (value instanceof Long) {
            return (Long) value;
        }
        return Long.valueOf(String.valueOf(value));
    }
    
    public void clearAgentsTable() {
        DefaultTableModel model = (DefaultTableModel) this.agentsTable.getModel();
        model.setRowCount(0);
        agentsTable.clearSelection();
        agentsTable.revalidate();
        agentsTable.repaint();
    }
    public void clearOperationsTable() {
        DefaultTableModel model = (DefaultTableModel) this.operationsTable.getModel();
        model.setRowCount(0);
        operationsTable.clearSelection();
        operationsTable.revalidate();
        operationsTable.repaint();
    }

    public JTable getOperationsTable() {
        return operationsTable;
    }

    public void setOperationsTable(JTable operationsTable) {
        this.operationsTable = operationsTable;
    }

    public Graphic getGraphic() {
        return graphic;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel agentsPanel;
    private javax.swing.JScrollPane agentsScrollPane;
    private javax.swing.JScrollPane agentsScrollPane1;
    private javax.swing.JTable agentsTable;
    private javax.swing.JPanel graphicPanel;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JButton operationsButton;
    private javax.swing.JPanel operationsPanel;
    private javax.swing.JTable operationsTable;
    // End of variables declaration//GEN-END:variables
}
